name: 'Find Online Runner with Tag'
description: 'This action finds an online runner with a specific tag.'
inputs:
  runner-labels:
    description: 'Runner labels to use (space, comma, or semicolon separated)'
    required: true
  include-organization-runners:
    description: 'Include organization runners'
    required: false
    default: 'false'
  github-token:
    description: 'GitHub token'
    required: true
    default: '${{ github.token }}'

branding:
  icon: "check-circle"
  color: "blue"
runs:
  using: 'node20'
  main: 'dist/index.js'